### ISSUE TITLE
TextField and pasting support...?

### ISSUE THREAD

**Issue by En3Tho** [migueldeicaza/gui.cs#1470]
Is it completely supported? On Win10 text pasting is quite slow and most importantly: data is corrupted.
This is the original string (from UiCatalog source):
var s = String.Format (String.Format ("{{0,{0}}}", -_nameColumnWidth), Scenario.ScenarioMetadata.GetName (Scenarios [item]));

![image](https://user-images.githubusercontent.com/37334640/134763731-ccfc4a64-ff19-4c58-b399-0127abe3272f.png)

This is a result of multiple pasting. Not even once the original string got copied in the right way.

**Comment by En3Tho** [comment]
Also, for some reason I cannot really catch Ctrl-V event manually, "V" is just nonexisting, only "CtrlMask" is shown. Pasting starts right after "V" is pressed and shadows it.

**Comment by tznind** [comment]
Are you using the menus? or the Terminal itself (e.g. powershell)

I've just tested and the in app paste works:

![image](https://user-images.githubusercontent.com/31306100/134765993-13706a9c-96b9-436f-a571-c06697658d6d.png)
_Works_

But the Powershell OS clipboard pasting feature has the issue you describe

![image](https://user-images.githubusercontent.com/31306100/134766076-ae8154b2-4f36-4f06-9d3f-839bbb093510.png)
_Does not work_

I am guessing the Powershell paste does a series of keypresses to type the text into the console and it probably runs into some race condition or something @BDisp?

**Comment by En3Tho** [comment]
@tznind You are correct. I'm using powershell. I came to the same conclusion as you have. If there are too many keystrokes then some of them are skipped.

**Comment by BDisp** [comment]
The console mode are configured to handle all the keystrokes from the application and not from the console. On the `TextView` pressing `Ctrl+C` copy to the clipboard handling from the application and not from the console. `Ctrl+Y` paste to the `TextView` handled by the application too. So, pressing `Ctrl+C` and `Ctrl+V` doesn't invoke the console keystroke and only it's possible to copy and paste from the console through the console popup menu. With `WindowsDriver` some keys are being eaten without the `WindowsConsole.InputRecord` could receive them. With the `NetDriver`, almost all the keystrokes are received and only stops at "`[`".

**Comment by BDisp** [comment]
> I already found why it's stopping at "`[`" with the `NetDriver`. I'll fix it.

Fixed here https://github.com/migueldeicaza/gui.cs/pull/1448/commits/d06a1bba266c116f35cbe3b6102f3114ff7c5847

**Comment by En3Tho** [comment]
@BDisp Hey! Sorry to tag again like this but can you please tell if Clipboard support is "on" on Linux? Doesn't seem to work for me but maybe it's something I did that I've shoudn't: I've registered TextkeyUpEvent to listen to CtrlC and used Clipboard class to capture text inside. Is it supported?

**Comment by tznind** [comment]
Ctrl+C is likely to force terminate your process in quite a few terminals especially linux ones. 

I would avoid it, you might want to use y or d like Vim (https://tosbourn.com/copy-paste-vim/) or a seperate key combination entirely https://stackoverflow.com/questions/30507022/copy-text-from-nano-editor-to-shell

**Comment by En3Tho** [comment]
@tznind Thank you for advice. Afaik by default Gui.cs quits via Ctrl+Q combination. And I'm running my app inside Powershell. So basically what I've done is a small lightweright RedisViewer so I could use it via ssh (powershell is still needed remotely) instead of raw redis-cli. So Ctrl+C is a valid combination there.

**Comment by En3Tho** [comment]
The code for ui is here: https://github.com/En3Tho/Something-obviously-useless/blob/master/SomethingObviouslyUseless/PoshRedisViewer/UI.fs

That repo is something like a "heap of useless (this one is actually useful) stuff" and I'm kinda lazy to split it between repos

**Comment by tznind** [comment]
Ctrl+C is a universal standard for sending SIG TERM [inate] to your process.  Kind of like Alt+F4 in windows.  So even if you are only responding to Ctrl+Q the OS might be doing other stuff.

**Comment by BDisp** [comment]
Normally `Ctrl-C` in `Linux`, also like on `Windows`, is configured to not break the application, but as `Clipboard` on `Linux` is using a `BashRunner` which is executing a bash process to run `xclip`, pressing `Ctrl-C` breaks the application. Maybe could have a way to avoid this but I couldn't figure it out.

**Comment by En3Tho** [comment]
@BDisp I see. Thanks. I will try to use CtrlShiftC combo on Linux like @tznind adviced.

**Comment by En3Tho** [comment]
@BDisp Again sorry to bother but can you please help with this thing:
On ubuntu when I run the app natively or inside powershell hovering mouse upon a component automatically sets focus on that component. Can this be somehow solved? On windows there is no such thing.

**Comment by BDisp** [comment]
This isn't happens to me with the current main branch. You are referring to `Ubuntu` on `WSL` or a real `Ubuntu`? Inside powershell, do you meaning installed on `Ubuntu`? Can you provide a simple test with your settings or a screen print, please?

**Comment by BDisp** [comment]
Thanks. I want you try to run the current main branch which I think this is already fixed.

**Comment by En3Tho** [comment]
Tried main.

![image](https://user-images.githubusercontent.com/37334640/135149212-e30d6274-2728-4671-af6d-48999d5e8456.png)
When running from Powershell host.

When running from bash host app starts but the problem persists. I'm using touchpad on my laptop for navigating and views are getting focused over mouse hover. Note that I'm not actually clicking. I'm only moving the mouse (my finger is "glued" to touchpad).

https://ufile.io/r43ldrqr

I will try to find the source of exception tomorrow but this project was supposed to be a small helper module for posh (and I'm glad I did and thanks (BIG one) for your work), I don't know if I can find time to dig the problem out.

**Comment by BDisp** [comment]
Do you have `xclip` installed on `Linux`?

**Comment by En3Tho** [comment]
Yes, I've installed it as you've (and @tznind ) advised. Moved copy action to Ctrl+Y. PowerShell is only crashing with main, it works with latest nuget.

**Comment by En3Tho** [comment]
For some reason it works with PowerShell host now and I did literally nothing. Some kind of Ubuntu magic... Focus problem persist though.

**Comment by BDisp** [comment]
> For some reason it works with PowerShell host now and I did literally nothing. Some kind of Ubuntu magic...

Okay, so it was only a sporadic mistake. For whatever reason it can not complete the process.



> Focus problem persist though.

I had to reinstall `Windows 10` and at the moment I have no virtual machine with `Linux`. As soon as I can, I will check this.

**Comment by BDisp** [comment]
`Console.Write` on `NetDriver` is more faster now. See here https://github.com/migueldeicaza/gui.cs/pull/1484#issuecomment-945092937, please.
